export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

//---------------------------------------------------------------------

export const LOAD_BotS_REQUEST = "LOAD_BotS_REQUEST";
export const LOAD_BotS_SUCCESS = "LOAD_BotS_SUCCESS";
export const LOAD_BotS_FAILURE = "LOAD_BotS_FAILURE";

export const GET_Bot_REQUEST = "GET_Bot_REQUEST";
export const GET_Bot_SUCCESS = "GET_Bot_SUCCESS";
export const GET_Bot_FAILURE = "GET_Bot_FAILURE";

export const NEW_Bot_REQUEST = "NEW_Bot_REQUEST";

export const UPDATE_Bot_REQUEST = "UPDATE_Bot_REQUEST";
export const UPDATE_Bot_SUCCESS = "UPDATE_Bot_SUCCESS";
export const UPDATE_Bot_FAILURE = "UPDATE_Bot_FAILURE";

export const ADD_Bot_REQUEST = "ADD_Bot_REQUEST";
export const ADD_Bot_SUCCESS = "ADD_Bot_SUCCESS";
export const ADD_Bot_FAILURE = "ADD_Bot_FAILURE";

export const DELETE_Bot_REQUEST = "DELETE_Bot_REQUEST";
export const DELETE_Bot_SUCCESS = "DELETE_Bot_SUCCESS";
export const DELETE_Bot_FAILURE = "DELETE_Bot_FAILURE";

//---------------------------------------------------------------------

export const LOAD_INTENTS_REQUEST = "LOAD_INTENTS_REQUEST";
export const LOAD_INTENTS_SUCCESS = "LOAD_INTENTS_SUCCESS";
export const LOAD_INTENTS_FAILURE = "LOAD_INTENTS_FAILURE";

export const GET_INTENT_REQUEST = "GET_INTENT_REQUEST";
export const GET_INTENT_SUCCESS = "GET_INTENT_SUCCESS";
export const GET_INTENT_FAILURE = "GET_INTENT_FAILURE";

export const UPDATE_INTENT_REQUEST = "UPDATE_INTENT_REQUEST";
export const UPDATE_INTENT_SUCCESS = "UPDATE_INTENT_SUCCESS";
export const UPDATE_INTENT_FAILURE = "UPDATE_INTENT_FAILURE";

export const NEW_INTENT_REQUEST = "NEW_INTENT_REQUEST";

export const ADD_INTENT_REQUEST = "ADD_INTENT_REQUEST";
export const ADD_INTENT_SUCCESS = "ADD_INTENT_SUCCESS";
export const ADD_INTENT_FAILURE = "ADD_INTENT_FAILURE";

export const DELETE_INTENT_REQUEST = "DELETE_INTENT_REQUEST";
export const DELETE_INTENT_SUCCESS = "DELETE_INTENT_SUCCESS";
export const DELETE_INTENT_FAILURE = "DELETE_INTENT_FAILURE";

//---------------------------------------------------------------------

export const LOAD_CATEGORYS_REQUEST = "LOAD_CATEGORYS_REQUEST";
export const LOAD_CATEGORYS_SUCCESS = "LOAD_CATEGORYS_SUCCESS";
export const LOAD_CATEGORYS_FAILURE = "LOAD_CATEGORYS_FAILURE";

export const LOAD_PRODUCTS_REQUEST = "LOAD_PRODUCTS_REQUEST";
export const LOAD_PRODUCTS_SUCCESS = "LOAD_PRODUCTS_SUCCESS";
export const LOAD_PRODUCTS_FAILURE = "LOAD_PRODUCTS_FAILURE";

export const GET_PRODUCT_REQUEST = "GET_PRODUCT_REQUEST";
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
export const GET_PRODUCT_FAILURE = "GET_PRODUCT_FAILURE";

export const UPDATE_PRODUCT_REQUEST = "UPDATE_PRODUCT_REQUEST";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_FAILURE = "UPDATE_PRODUCT_FAILURE";

export const NEW_PRODUCT_REQUEST = "NEW_PRODUCT_REQUEST";

export const ADD_PRODUCT_REQUEST = "ADD_PRODUCT_REQUEST";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const ADD_PRODUCT_FAILURE = "ADD_PRODUCT_FAILURE";

export const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_FAILURE = "DELETE_PRODUCT_FAILURE";
